### ISSUE TITLE
Unable to add events to calendar with plugin version 3.0.0

### ISSUE THREAD

**Issue by FedericoMatera** [builttoroam/flutter_plugins#152]
Just updated to version 3.0.0 and I'm unable to save a new event. 

Got this error message:
`type 'NoSuchMethodError' is not a subtype of type 'Exception'`
`in DeviceCalendarPlugin.createOrUpdateEvent (package:device_calendar/src/device_calendar.dart:202:54)`

**Comment by vondeetzen** [comment]
I've setup an example repository here https://github.com/vondeetzen/dc_nosucherrormethod_example with a short tutorial how to reproduce the error. Ran into it a day before.

When I'm running the example project (https://github.com/builttoroam/flutter_plugins/tree/develop/device_calendar/example) it works. Currenlty tested only on iOS 13 simulator (iPhone 11). So I'm currently assuming that there was a mistake while setting device_calendar up or I'm using the code wrong. Permission for the calendar were added in `Info.plist`.

Running on macOS Catalina and Flutter

```
$ flutter --version
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (7 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
```

Exception thrown is

```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: type 'NoSuchMethodError' is not a subtype of type 'Exception'
#0      DeviceCalendarPlugin.createOrUpdateEvent (package:device_calendar/src/device_calendar.dart:202:54)
#1      _MyHomePageState.build.<anonymous closure> (package:dc_nosucherrormethod_example/main.dart:71:39)
<asynchronous suspension>
#2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
#3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
#7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
#8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.da<…>
```

Looked at `/[...shortened].../.pub-cache/hosted/pub.dartlang.org/device_calendar-3.0.0/lib/src/device_calendar.dart:202` and found the line:

```dart
_parsePlatformExceptionAndUpdateResult<String>(e, res);
```

For debugging purposes I've added a statement
```dart
print('e = >$e< and res.success = >${res.isSuccess}< and res.data=>${res.data}<');
_parsePlatformExceptionAndUpdateResult<String>(e, res);
```
before and got:

```
e = >NoSuchMethodError: The getter 'data' was called on null.
Receiver: null
Tried calling: data< and res.success = >false< and res.data=>null<
```
(linebreak was added by the print statement not by me).

**Comment by vondeetzen** [comment]
Small addition: 2.0.0 also does not work for me (same NoSuchMethodError issue). Everything working fine with 1.0.0+3.

**Comment by Brett09** [comment]
Thanks for the details @FedericoMatera, @vondeetzen. I've had a look and found out I didn't put a null check for `Uri` property for the event - `event.url`

I'll make sure to add this into next update, as a workaround for now, please set an empty string to the url property of the event: `event.url = Uri.dataFromString('')`

**Comment by Brett09** [comment]
@FedericoMatera, @vondeetzen, a hotfix `v3.0.0+1` has been released now, update the dependency and you shouldn't be getting the error message anymore. You can discard the workaround.

**Comment by FedericoMatera** [comment]
Hi @Brett09 ,
now I have a different error:
`Failed assertion: boolean expression must not be null`
`at DeviceCalendarPlugin.createOrUpdateEvent (package:device_calendar/src/device_calendar.dart:170:15)`

`allDay` is nullable, i think

**Comment by FedericoMatera** [comment]
I created this PR:
https://github.com/builttoroam/flutter_plugins/pull/157

**Comment by nickrandolph** [comment]
@FedericoMatera thank you for the patience and contribution. We'll get this reviewed (I've done an initial pass already and it looks good) and merged asap.

**Comment by LOG-TAG** [comment]
recently started using this one, thanks for all contributors 
```
flutter: persmission is granted
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
```

using this ^3.0.0+3 version what is the temporary workaround? which version I should use? I'm using `_deviceCalendarPlugin.createOrUpdateEvent` only!
